name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu环境而非Arch Linux
    
    steps:
      - name: Install essential tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 openjdk-11-jdk bc bison build-essential \
            ccache curl flex g++-multilib gcc-multilib gnupg gperf imagemagick \
            lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync \
            schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
          repo --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up ccache
        run: |
          echo 'export USE_CCACHE=1' >> ~/.bashrc
          echo 'export CCACHE_SIZE=50G' >> ~/.bashrc
          ccache -M 50G
          source ~/.bashrc


      - name: Run kernel build script
        run: |
          export PATH=~/bin:$PATH  # 确保repo在PATH中
          chmod +x build.sh
          ./build.sh
        env:
          CONFIG_KERNELSU: true
          KERNELSU_TAG: main
          CONFIG_DOCKER: false
          CONFIG_ROOTGUARD: false
          DEVICE_NAME: LUNAA
          CONFIG_LTO: full

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            *.zip
            compile.log
          retention-days: 7  # 构建产物保留7天
