name: Build Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    steps:

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S base-devel git wget curl zstd tar python3 openssh --noconfirm
          
          # 安装 repo 工具（明确设置 PATH 并验证）
          mkdir -p ~/bin
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo mv ~/bin/repo /usr/bin/repo
          
          
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Execute build script
        run: |
          # 重新加载环境变量
          source /etc/environment
          
          # 验证 builder 用户的 PATH 和 repo 命令
          sudo -u builder bash -c 'echo "builder PATH: $PATH"'
          sudo -u builder bash -c 'which repo'
          sudo -u builder bash -c 'repo --version'
          
          sudo chmod +x build.sh
          sudo -u builder bash -c "sudo bash ./build.sh"
        env:
          CONFIG_KERNELSU: true
          KERNELSU_TAG: main
          CONFIG_DOCKER: false
          CONFIG_ROOTGUARD: false
          DEVICE_NAME: LUNAA
          CONFIG_LTO: full

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-results
          path: |
            *.zip
            compile.log
          retention-days: 7
