name: Build Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S base-devel git wget curl zstd tar python3 openssh --noconfirm
          # 安装 repo 工具
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

      - name: Execute build script
        run: |
          # 设置 PATH 包含 repo
          export PATH=~/bin:$PATH
          chmod +x build.sh
          sudo -u builder ./build.sh
        env:
          CONFIG_KERNELSU: true
          KERNELSU_TAG: main
          CONFIG_DOCKER: false
          CONFIG_ROOTGUARD: false
          DEVICE_NAME: LUNAA
          CONFIG_LTO: full

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-results
          path: |
            *.zip
            compile.log
          retention-days: 7
