name: Build Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    steps:

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S base-devel git wget curl zstd tar python3 openssh --noconfirm
          
          # 安装 repo 工具（明确设置 PATH 并验证）
          mkdir -p ~/bin
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          
          # 临时生效 PATH（避免 .bashrc 未加载问题）
          export PATH=~/bin:$PATH
          echo "当前 PATH: $PATH"
          repo --version  # 验证 repo 安装
          
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Execute build script
        run: |
          # 为 builder 用户设置 PATH（关键修改）
          echo 'export PATH=~/bin:$PATH' >> /home/builder/.bashrc
          sudo chmod +x build.sh
          sudo -u builder bash -c "source /home/builder/.bashrc && bash ./build.sh"
        env:
          CONFIG_KERNELSU: true
          KERNELSU_TAG: main
          CONFIG_DOCKER: false
          CONFIG_ROOTGUARD: false
          DEVICE_NAME: LUNAA
          CONFIG_LTO: full

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-results
          path: |
            *.zip
            compile.log
          retention-days: 7
