name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
      options: --privileged

    steps:
      - name: Install Git
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Enable multilib repository
        run: |
          # 启用multilib仓库
          sed -i 's/^#Include = /Include = /g' /etc/pacman.d/mirrorlist
          sed -i 's/^#\s*\[multilib\]/[multilib]/g' /etc/pacman.conf
          sed -i 's/^#\s*Include = \/etc\/pacman.d\/mirrorlist/Include = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf
          pacman -Syy --noconfirm

      - name: Install base and multilib dependencies
        run: |
          pacman -S --noconfirm base-devel python python3 curl wget zstd sudo
          pacman -S --noconfirm --needed multilib-devel lib32-ncurses lib32-readline lib32-zlib

      - name: Setup yay
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          sudo -u builder git clone https://aur.archlinux.org/yay.git /home/builder/yay
          cd /home/builder/yay
          sudo -u builder makepkg -si --noconfirm
          cd "$GITHUB_WORKSPACE"

      - name: 安装python2-bin（若需要）
        run: |
          if pacman -Qs python2-bin &>/dev/null; then
            pacman -S --noconfirm python2-bin
          else
            sudo -u builder yay -S python2-bin --noconfirm
          fi
          cd "$GITHUB_WORKSPACE"

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          echo 'export PYTHON=/usr/bin/python3' >> ~/.bashrc  # 确保使用Python3
          source ~/.bashrc
          repo --version



      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
          repo --version

      - name: Run kernel build script
        run: |
          export PATH=~/bin:$PATH  # 确保repo在PATH中
          chmod +x build.sh
          ./build.sh
        env:
          CONFIG_KERNELSU: true
          KERNELSU_TAG: main
          CONFIG_DOCKER: false
          CONFIG_ROOTGUARD: false
          DEVICE_NAME: LUNAA
          CONFIG_LTO: full

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            *.zip
            compile.log
          retention-days: 7  # 构建产物保留7天
