name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: '设备名称'
        required: true
        default: 'LUNAA'
        type: choice
        options:
          - 9P
          - 9RT
          - LUNAA
      enable_kernelsu:
        description: '启用 KernelSU'
        required: true
        default: 'true'
        type: boolean
      enable_docker:
        description: '启用 Docker 支持'
        required: true
        default: 'false'
        type: boolean
      enable_rootguard:
        description: '启用 RootGuard'
        required: true
        default: 'false'
        type: boolean
      lto_type:
        description: 'LTO 类型'
        required: true
        default: 'full'
        type: choice
        options:
          - none
          - thin
          - full

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    container:
      image: archlinux:base-devel
      options: --privileged -v /workspace:/workspace

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          path: /workspace
          
      - name: 安装基础工具和 repo
        run: |
          pacman -Syu --noconfirm git base-devel wget curl openssh ccache python3 which
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "export PATH=~/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          echo "~/bin" >> $GITHUB_PATH
          repo --version
        working-directory: /workspace

      - name: 设置用户和工作目录
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          mkdir -p /workspace
          chown -R builder:builder /workspace
          ls -la /workspace
        working-directory: /workspace

      - name: 设置 ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: kernel-build-${{ github.sha }}
          max-size: 5G

      - name: 运行 build.sh 脚本
        run: |
          cd $SOURCE_PATH
          chmod +x build.sh
          sudo -u builder ./build.sh
        env:
          MAKEFLAGS: "-j$(nproc --all)"
        working-directory: /workspace

      - name: 显示 ccache 统计信息
        run: ccache -s
        working-directory: /workspace

      - name: 查找编译结果
        id: find_artifacts
        run: |
          echo "zip_file=$(ls $SOURCE_PATH/*.zip | grep -v backup || true)" >> $GITHUB_OUTPUT
          echo "rootguard_file=$(ls $SOURCE_PATH/rootguard-*.zip || true)" >> $GITHUB_OUTPUT
        working-directory: /workspace

      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-${{ github.event.inputs.device }}-${{ github.sha }}
          path: |
            ${{ steps.find_artifacts.outputs.zip_file }}
            ${{ steps.find_artifacts.outputs.rootguard_file }}
          retention-days: 7
